### ISSUE TITLE
Scala steward job is failing

### ISSUE THREAD

**Issue by tgodzik** [cornerman/chameleon#215]
Not sure if the repository is active anymore, but the Scala Steward is unable to run on the repo:
```
[info] done compiling
/opt/workspace/repos/cornerman/chameleon/build.sbt:72: error: reference to git is ambiguous;
it is imported twice in the same scope by
import _root_.com.github.sbt.git.GitPlugin.autoImport._
and import _root_.com.typesafe.sbt.GitPlugin.autoImport._
        val remote        = s"https://raw.githubusercontent.com/${githubRepo}/${git.gitHeadCommit.value.get}"
                                                                                ^
sbt.compiler.EvalException: Type error in expression
[error] sbt.compiler.EvalException: Type error in expression
[error] Use 'last' for the full log.
[warn] Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? (default: r)

	at org.scalasteward.core.io.process$.$anonfun$slurp$9(process.scala:54)
	at org.scalasteward.core.io.process$.$anonfun$slurp$9$adapted(process.scala:50)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
	at modify @ fs2.internal.Scope.close(Scope.scala:262)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
	at rethrow$extension @ fs2.Compiler$Target.$anonfun$compile$1(Compiler.scala:157)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
	at flatMap @ fs2.Pull$.$anonfun$compile$21(Pull.scala:1209)
	at update @ fs2.internal.Scope.releaseChildScope(Scope.scala:224)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
2022-12-21 09:28:52,727 INFO  ──────────── Total time: Steward cornerman/chameleon: 53s 635ms ────────────

```

**Comment by cornerman** [comment]
Thanks for reporting. This repo is indeed still active. I will check and try to reproduce!

**Comment by cornerman** [comment]
This is fixed - the failing line does not exist anymore, the scala-steward-repos issue mentions that it works again and we are receiving PRs :)

Thank you for all your work!
